/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AutorEntity } from './autorEntity'

export interface ApiResponseAutorEntity {
  data?: AutorEntity
  message?: string
  status?: number
}
