/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface AutorEntity {
  id?: number;
  nacionalidade?: string;
  nome?: string;
}
