/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { LivroEntity } from './livroEntity';

export interface ApiResponseLivroEntity {
  data?: LivroEntity;
  message?: string;
  status?: number;
}
