/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CategoriaEntity } from './categoriaEntity'

export interface ApiResponseCategoriaEntity {
  data?: CategoriaEntity
  message?: string
  status?: number
}
