/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface LivroDto {
  autor_id: number
  categoria_id: number
  id?: number
  isbn: string
  titulo: string
}
